DROP TABLE IF EXISTS trip CASCADE;
CREATE TABLE trip (
  id SERIAL PRIMARY KEY NOT NULL,
  device_id INT REFERENCES device(id) NOT NULL ON DELETE CASCADE,
  name VARCHAR(255),
  start TIMESTAMP,
  end TIMESTAMP
);